version: '3.8'

services:

  mongo:
    image: mongo:6.0.2
    container_name: mongodbnode
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

volumes:
  mongo_data:
    driver: local

networks:
  mongonet: {}